apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:
provisioner: topolvm.io
reclaimPolicy: Delete
volumeBindingMode:
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.io/device-class: vg1
